#!/usr/bin/env bash
set -Eeuo pipefail

usage() {
  cat <<'USAGE'
ParallaX VPS uninstaller.

Easy mode:
  bash scripts/uninstall-vps.sh

The guided wizard removes ParallaX from one VPS and can remove the local client
configuration generated by scripts/deploy-vps.sh.

Explicit mode:
  bash scripts/uninstall-vps.sh --host root@1.2.3.4

Options:
  --host <ssh-target>              SSH target, for example root@1.2.3.4.
  --ssh-port <port>                SSH port. Defaults to 22.
  --remote-bin <path>              Remote plx binary path. Defaults to /usr/local/bin/plx.
  --remote-config <path>           Remote server config path. Defaults to /etc/parallax/parallax.toml.
  --service-name <name>            systemd service name. Defaults to parallax.
  --local-dir <path>               Local deploy directory. Defaults to target/parallax-deploy/<host>/.
  --remove-local                   Remove the local deploy directory. Default.
  --keep-local                     Keep the local deploy directory.
  --remove-bbr                     Remove ParallaX BBR + socket-buffer sysctl persistence files. Default.
  --keep-bbr                       Keep ParallaX BBR + socket-buffer sysctl persistence files.
  --remove-parca-agent             Also remove the parca-agent snap package if installed.
  --keep-parca-agent               Keep the parca-agent snap package. Default.
  --remove-ufw-rule                Remove UFW rules that have the ParallaX comment. Default.
  --keep-ufw-rule                  Keep UFW rules.
  --remove-user                    Remove the parallax system user created by deploy-vps.sh. Default.
  --keep-user                      Keep the parallax system user.
  --sudo                           Always use sudo on the VPS.
  --no-sudo                        Never use sudo on the VPS.
  --dry-run                        Print the cleanup plan without changing anything.
  --yes                            Skip the final confirmation prompt.
  --non-interactive                Never prompt; requires --host and --yes unless --dry-run is used.
  -h, --help                       Show this help.
USAGE
}

die() {
  printf 'error: %s\n' "$*" >&2
  exit 1
}

log() {
  printf '\033[1;34m==>\033[0m %s\n' "$*" >&2
}

warn() {
  printf '\033[1;33mwarning:\033[0m %s\n' "$*" >&2
}

trim_space() {
  local value=$1
  value="${value#"${value%%[![:space:]]*}"}"
  value="${value%"${value##*[![:space:]]}"}"
  printf '%s' "$value"
}

tolower_one() {
  trim_space "$(printf '%s' "$1" | tr '[:upper:]' '[:lower:]')"
}

have_tty_stdio() {
  [[ -t 0 && -t 1 ]]
}

prompt_line_or_default() {
  local prompt=$1 default=$2 value
  if [[ -n "$default" ]]; then
    printf '%s [%s]: ' "$prompt" "$default" >&2
  else
    printf '%s: ' "$prompt" >&2
  fi
  IFS= read -r value || die "input cancelled"
  value="$(trim_space "$value")"
  [[ -n "$value" ]] || value=$default
  printf '%s' "$value"
}

prompt_line_nonempty() {
  local prompt=$1 value
  while true; do
    value="$(prompt_line_or_default "$prompt" "")"
    [[ -n "$value" ]] && break
    warn "this value is required"
  done
  printf '%s' "$value"
}

prompt_yes_no() {
  local prompt=$1 default=$2 suffix value lc
  lc="$(tolower_one "$default")"
  case "$lc" in
    y|yes) suffix='[Y/n]' ;;
    n|no) suffix='[y/N]' ;;
    *) suffix='[y/n]' ;;
  esac

  while true; do
    printf '%s %s ' "$prompt" "$suffix" >&2
    IFS= read -r value || die "input cancelled"
    value="$(trim_space "$value")"
    [[ -n "$value" ]] || value=$default
    lc="$(tolower_one "$value")"
    case "$lc" in
      y|yes) return 0 ;;
      n|no) return 1 ;;
      *) warn "answer yes or no" ;;
    esac
  done
}

interactive_banner() {
  cat <<'BANNER'

-----------------------------------------------------------
ParallaX VPS uninstall -- guided cleanup
-----------------------------------------------------------

You will answer a few prompts. Brackets show defaults; press Enter to keep them.

This removes ParallaX server artifacts from the VPS and can remove the local
client config directory generated by the deploy script.
-----------------------------------------------------------

BANNER
}

shell_quote() {
  local value=${1//\'/\'\\\'\'}
  printf "'%s'" "$value"
}

repo_root() {
  local script_dir
  script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  cd "$script_dir/.." && pwd
}

safe_name() {
  printf '%s' "$1" | tr -c 'A-Za-z0-9_.-' '_'
}

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "missing required command: $1"
}

require_no_space() {
  local name=$1 value=$2
  [[ "$value" != *" "* ]] || die "$name must not contain spaces: $value"
}

require_no_control() {
  local name=$1 value=$2
  [[ ! "$value" =~ [[:cntrl:]] ]] || die "$name must not contain control characters"
}

require_safe_remote_path() {
  local name=$1 value=$2
  [[ "$value" == /* ]] || die "$name must be an absolute path: $value"
  require_no_space "$name" "$value"
  require_no_control "$name" "$value"
}

require_safe_service_name() {
  local name=$1 value=$2
  [[ -n "$value" ]] || die "$name must not be empty"
  [[ "$value" =~ ^[A-Za-z0-9_.@-]+$ ]] || \
    die "$name must contain only letters, numbers, dot, underscore, dash, or @: $value"
}

require_safe_ssh_target() {
  local value=$1
  [[ -n "$value" ]] || die "missing SSH target"
  [[ "$value" != -* ]] || die "--host must not start with '-': $value"
  require_no_space "--host" "$value"
  require_no_control "--host" "$value"
}

require_safe_ssh_port() {
  local value=$1
  [[ "$value" =~ ^[0-9]+$ ]] || die "--ssh-port must be a number: $value"
}

resolve_sudo_mode() {
  case "$REMOTE_SUDO" in
    auto)
      if [[ "$SSH_TARGET" == root@* || "$SSH_TARGET" == "root" ]]; then
        REMOTE_SUDO=""
      else
        REMOTE_SUDO="sudo"
      fi
      ;;
    sudo) REMOTE_SUDO="sudo" ;;
    none) REMOTE_SUDO="" ;;
    *) die "remote sudo mode is invalid" ;;
  esac
}

absolute_local_path() {
  local path=$1
  case "$path" in
    /*) printf '%s' "$path" ;;
    *) printf '%s/%s' "$ROOT" "$path" ;;
  esac
}

validate_local_dir_for_removal() {
  local dir=$1 base
  base="$ROOT/target/parallax-deploy"
  [[ -n "$dir" ]] || die "local directory is empty"
  [[ "$dir" != "/" ]] || die "refusing to remove /"
  [[ "$dir" != "$HOME" ]] || die "refusing to remove HOME"
  [[ "$dir" != "$ROOT" ]] || die "refusing to remove repository root"
  [[ "$dir" != "$base" ]] || die "refusing to remove the whole deploy directory"
  [[ "$dir" != *"/../"* && "$dir" != *"/.." && "$dir" != "../"* && "$dir" != ".." ]] || \
    die "refusing to remove a path containing '..': $dir"

  if [[ "$dir" == "$base"/* ]]; then
    return 0
  fi
  if [[ -f "$dir/parallax.client.toml" || -f "$dir/parallax.server.toml" ]]; then
    return 0
  fi
  die "refusing to remove a local directory that does not look like a ParallaX deploy directory: $dir"
}

set_default_local_dir() {
  if [[ -z "$LOCAL_DIR" ]]; then
    LOCAL_DIR="$ROOT/target/parallax-deploy/$(safe_name "$SSH_TARGET")"
  else
    LOCAL_DIR="$(absolute_local_path "$LOCAL_DIR")"
  fi
}

interactive_configure() {
  interactive_banner
  SSH_TARGET="$(prompt_line_nonempty "SSH target, for example root@1.2.3.4")"
  SSH_PORT="$(prompt_line_or_default "SSH port" "$SSH_PORT")"

  if ! prompt_yes_no "Use the standard ParallaX install paths?" "y"; then
    REMOTE_BIN="$(prompt_line_or_default "Remote plx binary path" "$REMOTE_BIN")"
    REMOTE_CONFIG="$(prompt_line_or_default "Remote server config path" "$REMOTE_CONFIG")"
    SERVICE_NAME="$(prompt_line_or_default "systemd service name" "$SERVICE_NAME")"

    printf '\nRemote privilege mode:\n' >&2
    printf '  1) auto: root SSH users skip sudo; other users use sudo\n' >&2
    printf '  2) always sudo\n' >&2
    printf '  3) never sudo\n' >&2
    local sudo_pick sudo_lc
    sudo_pick="$(prompt_line_or_default "Privilege selection" "1")"
    sudo_lc="$(tolower_one "$sudo_pick")"
    case "$sudo_lc" in
      1|auto|'') REMOTE_SUDO="auto" ;;
      2|sudo) REMOTE_SUDO="sudo" ;;
      3|none|no|"no sudo") REMOTE_SUDO="none" ;;
      *) die "unknown privilege selection: $sudo_pick" ;;
    esac
  fi

  ROOT="$(repo_root)"
  set_default_local_dir

  if prompt_yes_no "Remove the local generated config directory?" "y"; then
    REMOVE_LOCAL="1"
    LOCAL_DIR="$(prompt_line_or_default "Local deploy directory" "$LOCAL_DIR")"
    LOCAL_DIR="$(absolute_local_path "$LOCAL_DIR")"
  else
    REMOVE_LOCAL="0"
  fi

  if prompt_yes_no "Remove ParallaX BBR + socket-buffer sysctl persistence files from the VPS?" "y"; then
    REMOVE_BBR="1"
  else
    REMOVE_BBR="0"
  fi

  if prompt_yes_no "Also remove the parca-agent snap package if installed?" "n"; then
    REMOVE_PARCA_AGENT="1"
  else
    REMOVE_PARCA_AGENT="0"
  fi

  printf '\n' >&2
}

print_plan() {
  cat <<PLAN

Uninstall plan:
  SSH target:             $SSH_TARGET
  SSH port:               $SSH_PORT
  Remote service:         $SERVICE_NAME.service
  Remote binary:          $REMOTE_BIN
  Remote config:          $REMOTE_CONFIG
  Remote sudo:            ${REMOTE_SUDO:-none}
  Remove sysctl files:    $REMOVE_BBR
  Remove Parca Agent:     $REMOVE_PARCA_AGENT
  Remove UFW rules:       $REMOVE_UFW_RULE
  Remove parallax user:   $REMOVE_USER
  Remove local configs:   $REMOVE_LOCAL
  Local config directory: $LOCAL_DIR
PLAN
}

confirm_or_exit() {
  [[ "$YES" == "1" || "$DRY_RUN" == "1" ]] && return 0
  [[ "$NON_INTERACTIVE" != "1" ]] || die "--non-interactive needs --yes or --dry-run"
  have_tty_stdio || die "confirmation needs an interactive terminal; pass --yes only if you are sure"

  local answer
  printf '\nType UNINSTALL to continue: ' >&2
  IFS= read -r answer || die "confirmation cancelled"
  [[ "$answer" == "UNINSTALL" ]] || die "confirmation did not match; nothing changed"
}

remote_uninstall() {
  local q_sudo q_remote_bin q_remote_config q_service_name q_remove_bbr q_remove_parca q_remove_ufw q_remove_user
  q_sudo="$(shell_quote "$REMOTE_SUDO")"
  q_remote_bin="$(shell_quote "$REMOTE_BIN")"
  q_remote_config="$(shell_quote "$REMOTE_CONFIG")"
  q_service_name="$(shell_quote "$SERVICE_NAME")"
  q_remove_bbr="$(shell_quote "$REMOVE_BBR")"
  q_remove_parca="$(shell_quote "$REMOVE_PARCA_AGENT")"
  q_remove_ufw="$(shell_quote "$REMOVE_UFW_RULE")"
  q_remove_user="$(shell_quote "$REMOVE_USER")"

  local remote_script
  remote_script=$(cat <<'REMOTE'
set -Eeuo pipefail
export PATH="$PATH:/usr/sbin:/sbin"

: "${SUDO:=}"
: "${REMOTE_BIN:?missing REMOTE_BIN}"
: "${REMOTE_CONFIG:?missing REMOTE_CONFIG}"
: "${SERVICE_NAME:?missing SERVICE_NAME}"
: "${REMOVE_BBR:=1}"
: "${REMOVE_PARCA_AGENT:=0}"
: "${REMOVE_UFW_RULE:=1}"
: "${REMOVE_USER:=1}"

if [[ -n "$SUDO" ]] && ! command -v "$SUDO" >/dev/null 2>&1; then
  echo "$SUDO was requested but is not installed on the VPS" >&2
  exit 1
fi

SERVICE_UNIT="$SERVICE_NAME.service"
SERVICE_PATH="/etc/systemd/system/$SERVICE_UNIT"
PARCA_SERVICE="parca-agent.service"
PARCA_SERVICE_PATH="/etc/systemd/system/$PARCA_SERVICE"

run_root() {
  if [[ -n "$SUDO" ]]; then
    "$SUDO" "$@"
  else
    "$@"
  fi
}

remove_file() {
  local path=$1
  if [[ -e "$path" || -L "$path" ]]; then
    run_root rm -f -- "$path"
    echo "removed $path"
  else
    echo "missing $path"
  fi
}

remove_dir_tree() {
  local path=$1
  if [[ -d "$path" && ! -L "$path" ]]; then
    run_root rm -rf -- "$path"
    echo "removed $path"
  else
    echo "missing $path"
  fi
}

remove_dir_if_empty() {
  local path=$1
  if [[ -d "$path" && ! -L "$path" ]]; then
    run_root rmdir "$path" >/dev/null 2>&1 || true
  fi
}

stop_disable_unit() {
  local unit=$1 path=$2 exists=0
  [[ -f "$path" ]] && exists=1
  if command -v systemctl >/dev/null 2>&1; then
    if systemctl list-unit-files --no-legend "$unit" 2>/dev/null | grep -q .; then
      exists=1
    fi
    if systemctl list-units --all --no-legend "$unit" 2>/dev/null | grep -q .; then
      exists=1
    fi
    if [[ "$exists" == "1" ]]; then
      run_root systemctl stop "$unit" || true
      run_root systemctl disable "$unit" || true
      run_root systemctl reset-failed "$unit" || true
    fi
  elif [[ "$exists" == "1" ]]; then
    echo "systemctl not found; removing unit file only"
  fi
}

remove_parallax_service() {
  stop_disable_unit "$SERVICE_UNIT" "$SERVICE_PATH"
  remove_file "$SERVICE_PATH"
}

remove_parca_service() {
  local owned=0
  if [[ -f "$PARCA_SERVICE_PATH" ]] && grep -q '/etc/parallax/polarsignals' "$PARCA_SERVICE_PATH"; then
    owned=1
  fi

  if [[ "$owned" == "1" ]]; then
    stop_disable_unit "$PARCA_SERVICE" "$PARCA_SERVICE_PATH"
    remove_file "$PARCA_SERVICE_PATH"
  elif [[ -f "$PARCA_SERVICE_PATH" ]]; then
    echo "kept $PARCA_SERVICE_PATH because it does not look ParallaX-generated"
  else
    echo "missing $PARCA_SERVICE_PATH"
  fi

  remove_file /etc/parallax/polarsignals.env
  remove_file /etc/parallax/polarsignals.token

  if [[ "$REMOVE_PARCA_AGENT" == "1" ]]; then
    if command -v snap >/dev/null 2>&1 && run_root snap list parca-agent >/dev/null 2>&1; then
      run_root snap remove parca-agent || true
    else
      echo "parca-agent snap is not installed"
    fi
  fi
}

remove_bbr_files() {
  [[ "$REMOVE_BBR" == "1" ]] || return 0
  remove_file /etc/modules-load.d/parallax-bbr.conf
  remove_file /etc/sysctl.d/99-parallax-bbr.conf
  # The socket-buffer drop-in is written unconditionally by deploy-vps.sh (even
  # with --no-enable-bbr); clean it up under the same sysctl-persistence toggle.
  remove_file /etc/sysctl.d/99-parallax-netbuf.conf
  if command -v sysctl >/dev/null 2>&1; then
    run_root sysctl --system >/dev/null 2>&1 || true
  fi
}

remove_ufw_rules() {
  [[ "$REMOVE_UFW_RULE" == "1" ]] || return 0
  command -v ufw >/dev/null 2>&1 || return 0

  local status nums n
  status="$(run_root ufw status numbered 2>/dev/null || true)"
  grep -q 'Status: active' <<<"$status" || return 0
  nums="$(printf '%s\n' "$status" | awk '/ParallaX/ { line=$0; sub(/^.*\[/, "", line); sub(/\].*$/, "", line); gsub(/[[:space:]]/, "", line); if (line ~ /^[0-9]+$/) print line }' | sort -rn)"

  if [[ -z "$nums" ]]; then
    echo "no UFW rule with a ParallaX comment found"
    return 0
  fi

  for n in $nums; do
    run_root ufw --force delete "$n" || true
  done
}

remove_remote_files() {
  local config_dir replay_cache
  config_dir="$(dirname "$REMOTE_CONFIG")"
  replay_cache="$config_dir/parallax-replay.cache"

  remove_file "$REMOTE_BIN"
  remove_file "$REMOTE_CONFIG"
  # Sealed-secrets bundle written by the deploy's `plx seal` step (the matching
  # host.key lives under /var/lib/parallax and goes with that tree below).
  remove_file "$config_dir/parallax.secrets.enc"
  remove_file "$replay_cache"
  remove_dir_tree /var/lib/parallax
  remove_dir_if_empty "$config_dir"
  remove_dir_if_empty /etc/parallax
}

remove_service_user() {
  [[ "$REMOVE_USER" == "1" ]] || return 0
  if id -u parallax >/dev/null 2>&1; then
    # Best-effort: userdel refuses while processes still run as parallax (for
    # example another ParallaX service instance sharing the user).
    if run_root userdel parallax 2>/dev/null; then
      echo "removed parallax system user"
    else
      echo "warning: could not remove the parallax system user (still in use by another service?)" >&2
    fi
  else
    echo "parallax system user not present"
  fi
}

remove_parallax_service
remove_parca_service
remove_remote_files
remove_bbr_files
remove_ufw_rules
remove_service_user

if command -v systemctl >/dev/null 2>&1; then
  run_root systemctl daemon-reload || true
fi

echo "Remote ParallaX uninstall finished."
REMOTE
)

  if [[ "$DRY_RUN" == "1" ]]; then
    log "dry-run: remote cleanup script for $SSH_TARGET"
    printf '%s\n' "$remote_script"
    return 0
  fi

  log "Connecting to VPS and removing ParallaX artifacts"
  ssh -p "$SSH_PORT" "$SSH_TARGET" "SUDO=$q_sudo REMOTE_BIN=$q_remote_bin REMOTE_CONFIG=$q_remote_config SERVICE_NAME=$q_service_name REMOVE_BBR=$q_remove_bbr REMOVE_PARCA_AGENT=$q_remove_parca REMOVE_UFW_RULE=$q_remove_ufw REMOVE_USER=$q_remove_user bash -s" <<<"$remote_script"
}

local_uninstall() {
  [[ "$REMOVE_LOCAL" == "1" ]] || return 0
  if [[ ! -e "$LOCAL_DIR" ]]; then
    log "local config directory not found: $LOCAL_DIR"
    return 0
  fi

  validate_local_dir_for_removal "$LOCAL_DIR"

  if [[ "$DRY_RUN" == "1" ]]; then
    log "dry-run: rm -rf $(shell_quote "$LOCAL_DIR")"
    return 0
  fi

  log "Removing local generated config directory"
  rm -rf -- "$LOCAL_DIR"
}

SSH_TARGET=""
SSH_PORT="22"
REMOTE_BIN="/usr/local/bin/plx"
REMOTE_CONFIG="/etc/parallax/parallax.toml"
SERVICE_NAME="parallax"
LOCAL_DIR=""
REMOVE_LOCAL="1"
REMOVE_BBR="1"
REMOVE_PARCA_AGENT="0"
REMOVE_UFW_RULE="1"
REMOVE_USER="1"
REMOTE_SUDO="auto"
DRY_RUN="0"
YES="0"
NON_INTERACTIVE="0"
ROOT=""
ORIGINAL_ARG_COUNT=$#

while [[ $# -gt 0 ]]; do
  case "$1" in
    --host) SSH_TARGET=${2:-}; shift 2 ;;
    --ssh-port) SSH_PORT=${2:-}; shift 2 ;;
    --remote-bin) REMOTE_BIN=${2:-}; shift 2 ;;
    --remote-config) REMOTE_CONFIG=${2:-}; shift 2 ;;
    --service-name) SERVICE_NAME=${2:-}; shift 2 ;;
    --local-dir) LOCAL_DIR=${2:-}; shift 2 ;;
    --remove-local) REMOVE_LOCAL="1"; shift ;;
    --keep-local) REMOVE_LOCAL="0"; shift ;;
    --remove-bbr) REMOVE_BBR="1"; shift ;;
    --keep-bbr) REMOVE_BBR="0"; shift ;;
    --remove-parca-agent) REMOVE_PARCA_AGENT="1"; shift ;;
    --keep-parca-agent) REMOVE_PARCA_AGENT="0"; shift ;;
    --remove-ufw-rule) REMOVE_UFW_RULE="1"; shift ;;
    --keep-ufw-rule) REMOVE_UFW_RULE="0"; shift ;;
    --remove-user) REMOVE_USER="1"; shift ;;
    --keep-user) REMOVE_USER="0"; shift ;;
    --sudo) REMOTE_SUDO="sudo"; shift ;;
    --no-sudo) REMOTE_SUDO="none"; shift ;;
    --dry-run) DRY_RUN="1"; shift ;;
    --yes) YES="1"; shift ;;
    --non-interactive) NON_INTERACTIVE="1"; shift ;;
    -h|--help) usage; exit 0 ;;
    --) shift; break ;;
    -*) die "unknown option: $1" ;;
    *)
      if [[ -z "$SSH_TARGET" ]]; then
        SSH_TARGET=$1
      else
        die "unexpected argument: $1"
      fi
      shift
      ;;
  esac
done

if [[ "$ORIGINAL_ARG_COUNT" == "0" ]]; then
  have_tty_stdio || die "guided mode needs an interactive terminal; pass --host for explicit mode"
  interactive_configure
else
  [[ -n "$SSH_TARGET" ]] || die "missing SSH target; use --host or run with no arguments for guided mode"
  ROOT="$(repo_root)"
  set_default_local_dir
fi

require_safe_ssh_target "$SSH_TARGET"
require_safe_ssh_port "$SSH_PORT"
require_safe_remote_path "--remote-bin" "$REMOTE_BIN"
require_safe_remote_path "--remote-config" "$REMOTE_CONFIG"
require_safe_service_name "--service-name" "$SERVICE_NAME"
resolve_sudo_mode
set_default_local_dir

[[ "$NON_INTERACTIVE" != "1" || "$YES" == "1" || "$DRY_RUN" == "1" ]] || \
  die "--non-interactive needs --yes or --dry-run"

if [[ "$DRY_RUN" != "1" ]]; then
  need_cmd ssh
fi

print_plan
confirm_or_exit
remote_uninstall
local_uninstall

if [[ "$DRY_RUN" == "1" ]]; then
  printf '\nDry run finished. Nothing was changed.\n'
else
  printf '\nParallaX uninstall finished.\n'
fi
